name: abrevva
description: >-
  The EVVA Flutter Module is a collection of tools to work with electronical
  EVVA access components. It allows for scanning and connecting via BLE.
version: 0.0.4
homepage: https://github.com/evva-sfw/abrevva-flutter
environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.2.2
  parameterized_test: ^2.0.0
  mocktail: ^1.0.4
  collection: ^1.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=2.0.0 <5.0.0'
  test: ^1.24.9
flutter:
  plugin:
    platforms:
      android:
        package: com.evva.xesar.abrevva
        pluginClass: AbrevvaPlugin
      ios:
        pluginClass: AbrevvaPlugin
