group 'com.evva.xesar.abrevva'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '2.4.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}


apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    if (project.android.hasProperty("namespace")) {
        namespace 'com.evva.xesar.abrevva'
    }

    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
    }

    defaultConfig {
        minSdkVersion 30
        consumerProguardFiles 'proguard-consumer-rules.pro'
    }
    repositories {
        mavenLocal()
        google()
        mavenCentral()
    }
    dependencies {
        testImplementation 'org.jetbrains.kotlin:kotlin-test'
        testImplementation 'io.mockk:mockk:1.14.11'
        testImplementation "org.junit.jupiter:junit-jupiter:5.10.0"
        implementation group: "com.evva.xesar", name: "abrevva-sdk-android", version: "5.0.0"
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
                events "passed", "skipped", "failed", "standardOut", "standardError"
                outputs.upToDateWhen { false }
                showStandardStreams = true
            }
        }
    }
}

dependencies {
    implementation 'androidx.lifecycle:lifecycle-process:2.11.0'
}

