name: 'flutter-setup'
description: 'installs flutter'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Flutter SDK
      uses: flutter-actions/setup-flutter@03a3a60436d95e16d110127785240139a633ce70 # v4.0
      with:
        channel: stable
        version: latest
        cache: true
        cache-sdk: true
        cache-key: flutter-cache

    - name: Update Flutter SDK
      run: flutter upgrade
      shell: bash

    - name: Install dependencies
      run: flutter pub get
      shell: bash
