name: 'flutter-setup'
description: 'installs flutter'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Setup Flutter SDK
      uses: flutter-actions/setup-flutter@v3
      with:
        channel: stable
        version: 3.3.0
    - name: print cwd & file
      run: cwd && ls -la
      shell: bash 
    - name: Install dependencies
      run: flutter pub get
      shell: bash
  
    - name: Cache pub-cache
      id: pub-cache
      uses: actions/cache@v4
      with:
        path: ~/.pub-cache
        key: pub-cache--${{ hashFiles('pubspec.lock') }}

    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: ~/.flutter
        key: flutter-sdk--${{ hashFiles('pubspec.lock') }}
