name: 'flutter-setup'
description: 'installs flutter'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Setup Flutter SDK
      uses: flutter-actions/setup-flutter@v3
      with:
        channel: stable
        version: latest
        cache: true
        cahce-sdk: true
        cache-key: flutter-cache--${{ hashFiles('pubspec.lock') }}

    - name: Install dependencies
      run: flutter pub get
      shell: bash