
on:
  workflow_call:
    inputs:
      destination:
        required: true
        type: string
jobs:
  setup-flutter:
    runs-on: ${{ inputs.destination }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install dependencies
        run: dart pub get

      - name: Cache pub-cache
        id: pub-cache
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-cache--${{ hashFiles('pubspec.lock') }}

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: ~/.flutter
          key: flutter-sdk--${{ hashFiles('pubspec.lock') }}
