name: Dart lint
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/flutter-setup.yml
        with:
          destination: ubuntu-latest

      - name: Analyze sources
        run: dart analyze
