name: Dart lint
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  Analyze_sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: ./.github/actions/flutter-setup
      - run: flutter analyze --no-fatal-infos --no-pub
