name: Dart lint
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/flutter-setup

      - name: Analyze sources
        run: flutter analyze --no-fatal-infos 
