name: Publish to pub.dev

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*" # Tag must be the trigger, defined on pub.dev in the package settings
# https://dart.dev/tools/pub/automated-publishing#hardening-security-with-tag-protection-rules-on-github
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pub.dev # is configured in repo settings with secrets
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@03a3a60436d95e16d110127785240139a633ce70 # v4.0
        with:
          channel: stable
          version: latest
          cache: true
          cache-sdk: true
          cache-key: flutter-cache

      - run: flutter pub get

      - uses: flutter-actions/setup-pubdev-credentials@2bee905b7704ff12e0d8366e69253e8429438170 # v1.1

      - run: flutter pub publish --force
