name: "test_release"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4

      - name: Debug inputs
        run: |
          echo "Type of release:  from user ${GITHUB_ACTOR}"
          git config --list

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: latest
          cache: true
          cache-sdk: true
          cache-key: flutter-cache

      - name: Update Flutter SDK
        run: flutter upgrade

      - name: Install dependencies
        run: flutter pub get

      - name: Cache node_modules
        id: node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            test-app/node_modules
            .yarn/cache
          key: node-modules


      - name: Install dependencies
        run: npm i

      - name: git config
        run: |
          git config user.name "test name"
          git config user.email "test email"

      - name: release-it --dry-run
        run: npx release-it --dry-run
