name: test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Flutter
        uses: ./.github/actions/flutter-setup
      - name: run web tests & prepare test-results.json
        run: flutter test --file-reporter="json:test-results.json"
      - name: Store Testresults
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: test-results.json
          path: ./test-results.json

  test_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Flutter
        uses: ./.github/actions/flutter-setup
      - name: Set up JDK 21
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: "gradle"
      - name: Setup Android SDK
        uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2
      - name: Cache Android SDK
        id: androidSdk
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
        with:
          path: ~/Android/Sdk
          key: androidSdk
      - run: example/android/gradlew
      - name: Run Tests
        run: make test-android

  test_ios:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Flutter
        uses: ./.github/actions/flutter-setup
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
#      - name: Install iOS Runtime
#        run: |
#          sudo xcrun simctl runtime add "iOS 18.2" || true
#      - name: Boot iPhone Simulator
#        run: |
#          UDID=$(xcrun simctl list devices | grep "iPhone 17 (" | grep -v Pro | head -1 | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})")
#          echo "Booting simulator with UDID: $UDID"
#          xcrun simctl boot "$UDID" || true
#      - name: Cache Pods
#        id: pods
#        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
#        with:
#          path: example/ios/Pods
#          key: pods-cache--${{ hashFiles('example/ios/podfile.lock') }}
#      - name: Cache Xcode DerivedData
#        uses: irgaly/xcode-cache@fd644652c5d3fd1f794edcdf839eb1dc03a9021f # v1.8.1
#        with:
#          key: xcode-deriveddata
      - name: Install Pods
        run: |
          cd example/ios
          pod install
      - name: Run Tests
        run: make test-ios
